services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - "3000:3000"
    networks:
      - network
    environment:
      - NODE_ENV=production
    env_file:
      -  .env
    command: ["npm", "run", "serve"]

  database:
    image: mysql:latest
    container_name: mysql_database
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network

volumes:
  db_data:

networks:
  network: