services:
  db:
    image: mysql:latest
    container_name: mysql_database
    restart: always
    env_file:
      - ../back/.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_dashboard
    restart: always
    depends_on:
      - db
    env_file:
      - ../back/.env
    ports:
      - "8080:80"
    networks:
      - network

volumes:
  db_data:

networks:
  network: