name: Déploiement du site
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Déploiement"
    runs-on: ubuntu-latest
    env:
      VITE_HOST_API: ${{ secrets.VITE_HOST_API }}
    steps:
      - name: "Fetch the repository"
        uses: actions/checkout@v4

      - name: "Set up Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Remplacez par la version Node.js souhaitée

      - name: "Install dependencies"
        run: |
          cd back && npm install && cd ..
          cd front && npm install

      - name: "Build the application"
        if: success()
        env:
          VITE_HOST_API: ${{ secrets.VITE_HOST_API }}
        run: |
          cd front && npm run build
          cd ..
          cd back && npm run build

      - name: "Deploy the app"
        if: success()
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          REMOTE_HOST: ${{ secrets.SSH_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          TARGET: "~/app"
          ARGS: "-rltgoDzO --delete --verbose --exclude=.env"
          SCRIPT_BEFORE: |
            cd /var/www/html && tar -cvf ${{ secrets.BACKUP_DIR }} *
          SCRIPT_AFTER: |
            mv ~/app/front/dist /var/www/html
            cd back && docker compose up -d
